<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * employeeGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employeeGroupRepository extends EntityRepository
{
}
